version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672

networks:
  rabbitmq_go_net:
#     driver: bridge
volumes:
  mongodb_data_container:

# sonar:
#   container_name: aiwin-rabbit
#   image: aiwin/rabbitmq-stomp:latest
#   ports:
#     - 61613:61613
#     - 15674:15674
#     - 15672:15672